// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CommentHandler is an autogenerated mock type for the CommentHandler type
type CommentHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *CommentHandler) Add() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// Delete provides a mock function with given fields:
func (_m *CommentHandler) Delete() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewCommentHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentHandler creates a new instance of CommentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentHandler(t mockConstructorTestingTNewCommentHandler) *CommentHandler {
	mock := &CommentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
